# Generated by Django 5.0.1 on 2024-01-25 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0002_rename_remaining_amount_contract_amount_due_and_more"),
        ("employee", "0001_initial"),
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="end_date",
            new_name="event_end_date",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="start_date",
            new_name="event_start_date",
        ),
        migrations.AddField(
            model_name="event",
            name="employee",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="employee.employee",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="contract",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="contracts.contract",
            ),
        ),
    ]
