# Generated by Django 5.0.1 on 2024-01-25 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0002_remove_client_commercial_contact_and_more"),
        ("contracts", "0001_initial"),
        ("employee", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contract",
            old_name="remaining_amount",
            new_name="amount_due",
        ),
        migrations.AddField(
            model_name="contract",
            name="employee",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contracts",
                to="employee.employee",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contracts",
                to="clients.client",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="creation_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
