# Generated by Django 5.0.1 on 2024-01-25 18:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0001_initial"),
        ("employee", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="commercial_contact",
        ),
        migrations.RemoveField(
            model_name="client",
            name="creation_date",
        ),
        migrations.RemoveField(
            model_name="client",
            name="last_update",
        ),
        migrations.AddField(
            model_name="client",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="client",
            name="employee",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clients",
                to="employee.employee",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
